[phases.setup]
nixPkgs = ['php81', 'nodePackages.npm', 'nodejs', 'symfony-cli', 'php81Packages.composer']

[phases.build]
cmds = [
	# API setup
	'composer validate',
	'composer install --no-dev --optimize-autoloader',
	'php bin/console cache:clear --env=prod',
	'composer dump-env prod',
	'symfony console doctrine:migrations:migrate',

	# Vue client setup
	'npm install',
	'npm run build',

	# env print
	'php bin/console debug:dotenv',
	'php bin/console debug:container --env-vars',
]

[start]
cmd = 'php -S 0.0.0.0:80'
